### ISSUE TITLE
Ensure that if an opened terminal is not on the workspace root folder it navigates to it

### ISSUE THREAD

**Issue by samuelpordeus** [samuelpordeus/vscode-elixir-test#25]
Discussed on #24 

As it is right now, for both commands involving the vs-code terminal, we open a new terminal when there isn't one already opened. But if there is, we don't ensure that it's on the root folder (from the workspace). And that could lead us into trouble.

We need to do something like this:
```
if not root -> cd to_root
else -> do nothing
```

**Comment by mracos** [comment]
Maybe this could be solved if we always use `fullPaths` for the files

**Comment by samuelpordeus** [comment]
let's go with that solution :point_up:

**Comment by msramos** [comment]
We can use this approach for individual files (' runTestFile'  and ' runTestAtCursor'), but the `runTestSuite` command must run from project's root.

**Comment by GuSilverFlame** [comment]
> Maybe this could be solved if we always use `fullPaths` for the files

`mix test` doesn't like it when you use the full path

**Comment by mracos** [comment]
So it's 👎to using full paths then, since they do not work. 😞

Because of that, I thought of some approaches:
- Going up recursively relative from the current test file until we find a `mix.exs`and then assume it is the project root.
- Get the ["opened" folder in vscode](https://code.visualstudio.com/api/references/vscode-api#workspace.workspaceFolders) and assume it is the project root (maybe it would not work with umbrella apps?)
- Going up recursively until we find a `.git` directory and assume it is the project root (maybe it does not work with git submodules?)

I rather like the first option, it seems to be the best one for me but maybe you folks have any other ideas? I'm all ears. 😄

**Comment by msramos** [comment]
Why no just `cd` the root folder?

**Comment by mracos** [comment]
But how do we know which one is the root folder?

**Comment by samuelpordeus** [comment]
I think that a good approach is to assume that the root folder of the Elixir App is the root folder of the vs-code workspace.

Using that, we have two options when the user tries to run the test suite outside root:
1) Warn him that he is not on the root
2) Create a new terminal on the root and run `mix test`

WDYT about these approaches? That could even be configurable 🤔

**Comment by GuSilverFlame** [comment]
I like options 2 and 3
3 is easier but 2 is less likely to cause problems to the user

**Comment by samuelpordeus** [comment]
Ok, just to move forward with this issue. We are going with option 3. PRs are welcome 😅

**Comment by msramos** [comment]
This is going to be included in the next release!
